### ISSUE TITLE
keras yolov4tiny 2ncnn

### ISSUE THREAD

**Issue by donaldlee2008** [MarsTechHAN/keras2ncnn#1]
[model.zip](https://github.com/MarsTechHAN/keras2ncnn/files/5291075/model.zip)

**Comment by MarsTechHAN** [comment]
Hi. I think you were not using the correct API to save the model. This is what inside the file:
![image](https://user-images.githubusercontent.com/10462805/94923899-318dbf00-04ef-11eb-930b-22ffd3c8caea.png)

**Comment by MarsTechHAN** [comment]
Closed for no additional information provided.
