### ISSUE TITLE
An issue in model conversion

### ISSUE THREAD

**Issue by rose-jinyang** [MarsTechHAN/keras2ncnn#11]
Hello
How are you?
Thanks for contributing this project.
I met an issue when converting the vggface2 model, which is based on ResNet50 model.

![image](https://user-images.githubusercontent.com/47862419/101328463-fde26300-38aa-11eb-9100-ebb87a0aa255.png)

I tried this conversion on both tf1.x  and tf2.x but failed.
I send the source Keras model.
https://we.tl/t-MjAHF2SPiK
Please fix the issue asap.
Thanks

**Comment by MarsTechHAN** [comment]
It should work since fac474a, version 0.1.1 on pip.

**Comment by rose-jinyang** [comment]
Thanks
