### ISSUE TITLE
Another issue in conversion

### ISSUE THREAD

**Issue by rose-jinyang** [MarsTechHAN/keras2ncnn#12]
Hello
How are you?
Thanks to your continuous updating.
I met an another issue when converting a Keras model with the latest converter.

![image](https://user-images.githubusercontent.com/47862419/101562827-1cf40880-3a03-11eb-891b-a7f09b2157c5.png)

This keras model works well on Keras 2.3.1 and Tensorflow 1.14.0.
I send the model.
https://we.tl/t-yaiIGvSxNs
Please fix this issue asap.
Thanks.

**Comment by MarsTechHAN** [comment]
Fixed in 5fe8ea6.
If you think this project help, please star it share to whom may need it :p

**Comment by rose-jinyang** [comment]
Thanks
