### ISSUE TITLE
Not same as the original model result

### ISSUE THREAD

**Issue by rose-jinyang** [MarsTechHAN/keras2ncnn#13]
Hello
How are you?
Thanks for your continuous updating.
I converted a keras model for predicting a liveness score of face, which is a binary classification model in general.
But the result from the ncnn model is NOT same as the original keras model.
In other words, the result from the ncnn model is always 1.0 for both real and fake face images.
I send the original keras model, the inference script and sample images.
https://we.tl/t-A0orRSIWn8
Please check and fix the issue asap.
Thanks.

**Comment by rose-jinyang** [comment]
Hi
How are you?
Not yet?

**Comment by MarsTechHAN** [comment]
It should work since f316f32.  I find a bug on translation of the fused activation, I think that's the cause.
I  also compare the output from the ncnn and keras, they yield almost the same. (You can try the new debugger for yourself).

**Comment by rose-jinyang** [comment]
Thanks

**Comment by rose-jinyang** [comment]
Hi
I checked but the result from ncnn model is too different from the original model.

The results from the Keras model are the following:
the real face: 0.31723082
the fake face: 0.1382943

The results from the NCNN model are the following:
the real face: 0.7100694
the fake face: 0.7893058

Could u check on your side again?
Thanks
