### ISSUE TITLE
Activation type relu6 is is not supported yet.

### ISSUE THREAD

**Issue by wangjing60755** [MarsTechHAN/keras2ncnn#27]
can you make it ok??

**Comment by MarsTechHAN** [comment]
sure, can you provide a sample graph?

**Comment by wangjing60755** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MarsTechHAN/keras2ncnn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月24日(星期三) 晚上6:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MarsTechHAN/keras2ncnn] Activation type relu6 is is not supported yet. (#27)





 
sure, can you provide a sample graph?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

hair_model_2.py (2.6K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2735623491c3cac89e7c1ba81336071806505555075350074e5752000d1b010e57514f0c0207561a530307020c00560f520d5b043539355f025c106b585951520f6a501a454f350a&t=exs_ftn_download&code=c5b45657




weights_280-0.9868.h5 (10.29M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2b343931c95f69cd9c7d40ad1f37001d05500b500d5400564c020b575f1a0600545014500956041f050d5a075a5356005803010039223245045d5e594d446d0059041401170e0a04591a5104390a&t=exs_ftn_download&code=a4919722

**Comment by MarsTechHAN** [comment]
This should be fixed since 943cd5c33dac2c09cd9a5d732e55ae8b90b97614.

**Comment by MarsTechHAN** [comment]
I will close this issue since it has been resolved.
