### ISSUE TITLE
Keras2ncnn can't support  Dense(8, activation = 'tanh', name='predictions') op

### ISSUE THREAD

**Issue by niuhaitaofeilong** [MarsTechHAN/keras2ncnn#40]
Keras2ncnn can't support  Dense(8, activation = 'tanh', name='predictions') op;
please add the op; the attachment is the model for test
[test_se4.zip](https://github.com/MarsTechHAN/keras2ncnn/files/7902025/test_se4.zip)

**Comment by MarsTechHAN** [comment]
I cannot open the zip file, but you can try to pull the newest file to test it.
![image](https://user-images.githubusercontent.com/10462805/151462629-615a1a31-fb39-479b-b2ac-cb7c3d25225c.png)
