### ISSUE TITLE
[ERROR] Failed to load structure descriptor from h5df file.

### ISSUE THREAD

**Issue by onexuan** [MarsTechHAN/keras2ncnn#43]
https://github.com/idealo/image-quality-assessment

python -m keras2ncnn -i weights_mobilenet_aesthetic_0.07.hdf5 -o ./

get this error 
Reading and parsing keras h5df file...
[ERROR] Failed to load structure descriptor from h5df file.
You may load a weight only file.
Such issue may caused by following ways:
	1. You are using model.save_weights instead of model.save
	2. You are trying to load a weight file download from somewhere.
If you are very confident of your file, please report a bug at:

**Comment by MarsTechHAN** [comment]
Hi. I think the error message is pretty clear. The model in the repo is just the weight and does not contain model parameters and structure. You need to export the model with both the structure and the weight.
![image](https://user-images.githubusercontent.com/10462805/153741384-8999144d-9c51-4161-9cd4-51c43eb052fb.png)
