### ISSUE TITLE
raise NotImplementedError  

### ISSUE THREAD

**Issue by weidom** [MarsTechHAN/keras2ncnn#5]
{'layer': {'class_name': 'ReLU', 'config': {'name': 're_lu', 'trainable': True, 'dtype': 'float32', 'max_value': None, 'negative_slope': 0.0, 'threshold': 0.0}, 'name': 're_lu', 'inbound_nodes': [[['batch_normalization', 0, 0, {}]]]}, 'weight': None}

'max_value': None   

为啥 relu 会有这个参数 ，是我的问题吗？   

请问大佬，我该怎么规避这个问题呢

**Comment by MarsTechHAN** [comment]
error log不太全，不好判断问题，github可以上传文件了，带上h5我跑一下吧

**Comment by MarsTechHAN** [comment]
Close due to long time no response, you can reopen it if you get the file.
