### ISSUE TITLE
Support for this model

### ISSUE THREAD

**Issue by adithyaxx** [MarsTechHAN/keras2ncnn#7]
This is a keras model which I would like converted to ncnn. Could you add support for conversion of this model?

https://github.com/AIZOOTech/FaceMaskDetection/blob/master/models/face_mask_detection.hdf5

**Comment by MarsTechHAN** [comment]
It should work since c52e15b :p

**Comment by adithyaxx** [comment]
Thank you for adding support. I get errors while I try to load the converted model in NCNN.

```
ParamDict read array element failed
ParamDict load_param failed
parse top_count failed
load_model error at layer 76, parameter file has inconsistent content.
```

**Comment by MarsTechHAN** [comment]
hmm...let me check that tomorrow

**Comment by MarsTechHAN** [comment]
I think I find the issue, but I have to talk with ncnn developers to see how I can solve it.

**Comment by adithyaxx** [comment]
Sure, let me know when you have found a solution!

**Comment by MarsTechHAN** [comment]
It should works since 2f86008 , can you have a try?

**Comment by MarsTechHAN** [comment]
Hi, it should works now.  e0f7c3e
