### ISSUE TITLE
转换问题

### ISSUE THREAD

**Issue by snell1** [MarsTechHAN/keras2ncnn#9]
你好，谢谢你的分享，我通过你的代码将一个h5模型转换成了ncnn模型，但有一个问题，生成的param文件各个层的顺序是乱的（虽然通过netron软件打开模型是正确的），请问有什么方法可以解决吗？谢谢

**Comment by snell1** [comment]
keras模型：https://pan.baidu.com/s/1iO5vqP-NR5xGVVgnQjF3Tg
提取码：l398

**Comment by MarsTechHAN** [comment]
应该可以了，修复了顺序的问题，你试试看能否运行？

**Comment by snell1** [comment]
你好，万分感谢！
目前转换得到的结果顺序上输入是对的了，但是依旧存在两个问题：
1、我的模型是双输入的，结果转换得到的只有单输入
2、最后的softmax貌似顺序还是不对，按理说应该在最后一行（不知道我的理解对不对）
如果有时间，麻烦你再看看是否真的存在我说的两个问题，再次表示感谢！









在 2020-12-06 20:33:12，"Martin Han" <notifications@github.com> 写道：

应该可以了，修复了顺序的问题，你试试看能否运行？

**Comment by MarsTechHAN** [comment]
呃，我注意到这个问题了...所以后来删掉了， 从 e0f7c3e 开始应该可以了

**Comment by MarsTechHAN** [comment]
哦，你的是双输入的，我确认一下

**Comment by MarsTechHAN** [comment]
测试了一下，188a4da 肯定可以了= =
